In [18]:
import pandas as pd, numpy as np
from pathlib import Path

from pyspark.sql import SparkSession
from pyspark.sql import functions as F  # F.count, F.max, F.upper ...
from pyspark.sql.functions import col

spark = (
    SparkSession.builder
        .appName("SparkML")
        .enableHiveSupport()
        .getOrCreate()
)

DATA_PATH = Path("./data")

26/10/15 13:10:05 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

In [12]:
titanic_sdf = spark.read.csv(str(DATA_PATH / "titanic_train.csv"), header=True, inferSchema=True)
titanic_sdf = titanic_sdf.cache()     # T
titanic_pdf = titanic_sdf.toPandas()

26/10/15 13:09:34 WARN CacheManager: Asked to cache already cached data.

In [13]:
titanic_pdf.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

In [14]:
titanic_sdf.limit(5).show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|   7.25| NULL|       S|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| NULL|       S|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   53.1| C123|       S|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|   8.05| NULL|       S|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+

In [15]:
titanic_pdf_2 = titanic_pdf.copy()
titanic_sdf_2 = titanic_sdf.select("*")

In [16]:
titanic_pdf_2["Extra_Fare"] = titanic_pdf_2["Fare"] * 10
titanic_sdf_2 = titanic_sdf_2.withColumn("Extra_Fare", col("Fare") * 10)

titanic_sdf_2.limit(5).show()
titanic_pdf_2.head()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+----------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|Extra_Fare|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+----------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|   7.25| NULL|       S|      72.5|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|   712.833|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| NULL|       S|     79.25|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   53.1| C123|       S|     531.0|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|   8.05| NULL|       S|      80.5|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+----------+

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Extra_Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S,72.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,712.833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S,79.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,531.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S,80.500

In [17]:
titanic_pdf_2["Fare"] = titanic_pdf_2["Fare"] + 20
titanic_sdf_2 = titanic_sdf_2.withColumn("Fare", col("Fare") + 20)

titanic_sdf_2.limit(5).show()
titanic_pdf_2.head()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+----------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|Extra_Fare|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+----------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|  27.25| NULL|       S|      72.5|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|91.2833|  C85|       C|   712.833|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282| 27.925| NULL|       S|     79.25|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   73.1| C123|       S|     531.0|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|  28.05| NULL|       S|      80.5|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+----------+

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Extra_Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,27.2500,None,S,72.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,91.2833,C85,C,712.833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,27.9250,None,S,79.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,73.1000,C123,S,531.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,28.0500,None,S,80.500

In [20]:
titanic_pdf_2["Fare"] = titanic_pdf_2["Fare"].astype(np.int64)
titanic_sdf_2 = titanic_sdf_2.withColumn("Fare", col("Fare").cast("Integer"))

titanic_sdf_2.limit(5).show()
titanic_pdf_2.head()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+----+-----+--------+----------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|Fare|Cabin|Embarked|Extra_Fare|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+----+-----+--------+----------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|  27| NULL|       S|      72.5|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|  91|  C85|       C|   712.833|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  27| NULL|       S|     79.25|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|  73| C123|       S|     531.0|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|  28| NULL|       S|      80.5|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+----+-----+--------+----------+

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Extra_Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,27,None,S,72.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,91,C85,C,712.833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,27,None,S,79.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,73,C123,S,531.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,28,None,S,80.500

In [22]:
titanic_sdf_2.withColumn("Extra_Fare", col("Fare") * 10).withColumn("Fare", col("Fare") + 20).withColumn("Fare", col("Fare").cast("Integer")).limit(5).show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+----+-----+--------+----------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|Fare|Cabin|Embarked|Extra_Fare|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+----+-----+--------+----------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|  47| NULL|       S|       270|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599| 111|  C85|       C|       910|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  47| NULL|       S|       270|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|  93| C123|       S|       730|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|  48| NULL|       S|       280|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+----+-----+--------+----------+

In [24]:
titanic_sdf_2 = titanic_sdf_2.withColumn("Extra_Fare", 10) # 오류

PySparkTypeError: [NOT_COLUMN] Argument `col` should be a Column, got int.

In [25]:
from pyspark.sql.functions import lit

In [27]:
titanic_sdf_2 = titanic_sdf_2.withColumn("Extra_Fare", lit(10))
titanic_sdf_2 = titanic_sdf_2.withColumn("New_Name", lit("Test_name"))

titanic_sdf_2.limit(5).show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+----+-----+--------+----------+---------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|Fare|Cabin|Embarked|Extra_Fare| New_Name|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+----+-----+--------+----------+---------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|  27| NULL|       S|        10|Test_name|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|  91|  C85|       C|        10|Test_name|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  27| NULL|       S|        10|Test_name|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|  73| C123|       S|        10|Test_name|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|  28| NULL|       S|        10|Test_name|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+----+-----+--------+----------+---------+

In [32]:
from pyspark.sql.functions import substring

titanic_sdf_2 = titanic_sdf_2.select("*", col("Sex").alias("Gender"))
titanic_sdf_2 = titanic_sdf_2.select("*", substring(col("Cabin"), 0, 1).alias("Cabin_First"))

titanic_sdf_2 = titanic_sdf_2.withColumn("Gender2", col("Sex")).withColumn("Cabin_First2", substring(col("Cabin"), 0, 1))

display(titanic_sdf_2.limit(5).toPandas())

26/10/15 13:22:08 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,Gender2,Cabin_First2,Gender,Cabin_First,Gender,Cabin_First,Gender,Cabin_First,Gender,Cabin_First
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,27,...,male,None,male,None,male,None,male,None,male,None
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,91,...,female,C,female,C,female,C,female,C,female,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,27,...,female,None,female,None,female,None,female,None,female,None
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,73,...,female,C,female,C,female,C,female,C,female,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,28,...,male,None,male,None,male,None,male,None,male,None

In [33]:
from pyspark.sql.functions import split

titanic_sdf_2 = titanic_sdf_2.withColumn("Name1", split(col("Name"), ",").getItem(0))
titanic_sdf_2 = titanic_sdf_2.withColumn("Name2", split(col("Name"), ",").getItem(1))

display(titanic_sdf_2.limit(5).toPandas())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,Gender,Cabin_First,Gender,Cabin_First,Gender,Cabin_First,Gender,Cabin_First,Name1,Name2
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,27,...,male,None,male,None,male,None,male,None,Braund,Mr. Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,91,...,female,C,female,C,female,C,female,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,27,...,female,None,female,None,female,None,female,None,Heikkinen,Miss. Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,73,...,female,C,female,C,female,C,female,C,Futrelle,Mrs. Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,28,...,male,None,male,None,male,None,male,None,Allen,Mr. William Henry

In [37]:
titanic_sdf_2 = titanic_sdf_2.withColumnRenamed("Gender", "Gender_Renamed")

display(titanic_sdf_2.limit(5).toPandas())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,Gender_Renamed,Cabin_First,Gender_Renamed,Cabin_First,Gender_Renamed,Cabin_First,Gender_Renamed,Cabin_First,Name1,Name2
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,27,...,male,None,male,None,male,None,male,None,Braund,Mr. Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,91,...,female,C,female,C,female,C,female,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,27,...,female,None,female,None,female,None,female,None,Heikkinen,Miss. Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,73,...,female,C,female,C,female,C,female,C,Futrelle,Mrs. Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,28,...,male,None,male,None,male,None,male,None,Allen,Mr. William Henry